document.addEventListener("DOMContentLoaded", loadData);
const $=(id)=>document.getElementById(id); const txt=(id,v)=>{if($(id))$(id).innerText=v??"—"};
function money(v){return `€${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
async function loadData(){
 try{
  const r=await fetch(`data.json?t=${Date.now()}`); if(!r.ok) throw new Error("data.json unavailable"); const d=await r.json(); const b=d.backtest||{}, p=d.positionPlan;
  txt("current-price",Number(d.currentPrice).toFixed(5)); txt("trend-regime",`${d.marketBias||""} ${d.trendRegime||"—"}`.trim()); txt("trend-score",`${d.trendScore??0}/${d.trendScoreMax??5}`); txt("vol-regime",d.volatilityRegime);
  let sig=d.signal||"NEUTRAL (WAIT)"; txt("signal",sig); $("signal").className=`value ${sig.includes("BUY")?"green":sig.includes("SELL")?"red":"blue"}`;
  txt("candidate",d.candidateSignal); txt("signal-reason",d.signalReason); txt("rsi",d.rsi); txt("macd",d.macdHist); txt("adx",d.adx); txt("dmi",`${d.plusDI??"—"} / ${d.minusDI??"—"}`); txt("ema50",d.ema50); txt("ema200",d.ema200);
  if(p&&p.valid){const q=p.recommended||{}; txt("pos-equity",money(p.equityEUR)); txt("pos-risk",`${p.appliedRiskPct}% / ${money(q.riskAtStopEUR)}`); txt("pos-units",`${Number(q.units||0).toLocaleString()} EUR (${Number(q.lots||0).toFixed(3)} lots)`); txt("pos-lev",`${Number(q.leverage||0).toFixed(2)}× ${q.usesLeverage?"(con apalancamiento)":"(sin apalancamiento)"}`); txt("stop-source",`${p.stopSource} / ${p.trend?.volatilityRegime||"—"}`); txt("stop-dist",`${Number(p.stopDistanceATR||0).toFixed(2)} ATR`); txt("stop-loss",Number(p.stopLoss).toFixed(5)); txt("take-profit",Number(p.takeProfit).toFixed(5)); txt("pos-rr",`${Number(q.rewardRisk||0).toFixed(2)}×`)} else { ["pos-equity","pos-risk","pos-units","pos-lev","stop-source","stop-dist","stop-loss","take-profit","pos-rr"].forEach(x=>txt(x,"—")); }
  txt("bt-window",`${d.backtestWindow?.start||"—"} → ${d.backtestWindow?.end||"—"}`); txt("bt-final",money(b.finalCapitalEUR)); txt("bt-return",`${b.totalReturn>=0?"+":""}${b.totalReturn??0}%`); txt("bt-win",`${b.winRate??0}%`); txt("bt-pf",b.profitFactor); txt("bt-sharpe",b.sharpe); txt("bt-dd",`${b.maxDrawdown??0}%`); txt("bt-r",`${b.expectancyR??0}R`); txt("bt-trades",b.totalTrades??0);
  $("trades").innerHTML=(d.trades||[]).slice(-20).reverse().map(t=>`<tr><td>${String(t.entry).slice(0,10)}</td><td>${String(t.exit).slice(0,10)}</td><td class="${t.side==='LONG'?'green':'red'}">${t.side}</td><td>${t.trendScore}/5 ${t.trendRegime}</td><td>${t.stopSource} ${Number(t.stopDistanceATR||0).toFixed(2)}ATR</td><td>${Number(t.units||0).toLocaleString()}</td><td>${Number(t.leverage||0).toFixed(2)}×</td><td class="${Number(t.profitEUR)>=0?'green':'red'}">${money(t.profitEUR)}</td><td>${Number(t.rMultiple||0).toFixed(2)}R</td><td>${Number(t.maeR||0).toFixed(2)} / ${Number(t.mfeR||0).toFixed(2)}</td><td>${t.reason}</td></tr>`).join("")||`<tr><td colspan="11">Sin operaciones completadas.</td></tr>`;
  draw(d.chart||{});
 }catch(e){console.error(e); txt("signal","Ejecuta Update EURUSD dashboard");}
}
function draw(c){const ctx=$("chart").getContext("2d"); new Chart(ctx,{type:"line",data:{labels:c.dates||[],datasets:[{label:"EUR/USD",data:c.prices||[],borderColor:"#60a5fa",borderWidth:2,pointRadius:0},{label:"EMA 50",data:c.ema50||[],borderColor:"#10b981",borderWidth:1,pointRadius:0},{label:"EMA 200",data:c.ema200||[],borderColor:"#f59e0b",borderWidth:1,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{labels:{color:"#cbd5e1"}}},scales:{x:{ticks:{color:"#94a3b8"},grid:{color:"#1e293b"}},y:{ticks:{color:"#94a3b8"},grid:{color:"#334155"}}}}});}
