"""Leakage-controlled ML meta-labeling for EUR/USD daily signals.

The ML layer does NOT invent direction. A broad technical rule proposes LONG/SHORT;
the model estimates whether that candidate is worth taking. Training is chronological,
outcomes must be fully known before a prediction date, and models are retrained only
periodically to reduce noise chasing.
"""
from __future__ import annotations

from dataclasses import dataclass, replace
import math
from typing import Iterable

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import brier_score_loss, roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from .strategy_engine import (
    PIP, Params, _commission, _metrics, _utc_ts, broad_candidate_row, features,
    pnl_eur, position_plan,
)

CORE_FEATURES = ["rsi_centered", "sma_gap", "macd_atr", "rv20", "adx", "ret5", "side"]
COMPACT_FEATURES = CORE_FEATURES + ["bb_z", "atr_pct", "ret20"]
FULL_FEATURES = COMPACT_FEATURES + ["ret1", "range_pct", "body_pct"]
FEATURE_SETS = {"core": CORE_FEATURES, "compact": COMPACT_FEATURES, "full": FULL_FEATURES}


@dataclass(frozen=True)
class MLParams:
    threshold: float = 0.55
    retrain_every_bars: int = 60
    min_train_events: int = 100
    calibration_fraction: float = 0.20
    feature_set: str = "core"
    max_train_years: int = 8
    C: float = 0.7
    min_validation_auc: float = 0.52


class ChronologicalPlattModel:
    """Simple logistic base + chronological Platt calibration."""
    def __init__(self, C: float = 0.7):
        self.base = Pipeline([
            ("scale", StandardScaler()),
            ("logit", LogisticRegression(C=C, class_weight="balanced", max_iter=2000, random_state=7)),
        ])
        self.calibrator = LogisticRegression(C=1.0, max_iter=1000, random_state=7)
        self.has_calibrator = False
        self.fitted = False
        self.validation = {}

    def fit(self, X: pd.DataFrame, y: pd.Series, calibration_fraction: float = 0.20):
        n = len(X)
        split = max(30, int(n * (1 - calibration_fraction)))
        split = min(split, n - 20)
        if split < 30 or y.iloc[:split].nunique() < 2:
            raise ValueError("Insufficient chronological class diversity for ML fit.")
        X_fit, y_fit = X.iloc[:split], y.iloc[:split]
        X_cal, y_cal = X.iloc[split:], y.iloc[split:]
        self.base.fit(X_fit, y_fit)
        p_raw = self.base.predict_proba(X_cal)[:, 1]
        if len(y_cal) >= 20 and y_cal.nunique() >= 2:
            eps = 1e-6
            logits = np.log(np.clip(p_raw, eps, 1-eps) / np.clip(1-p_raw, eps, 1-eps)).reshape(-1, 1)
            self.calibrator.fit(logits, y_cal)
            self.has_calibrator = True
            p = self.calibrator.predict_proba(logits)[:, 1]
        else:
            p = p_raw
        self.validation = {
            "events": int(len(y_cal)),
            "brier": float(brier_score_loss(y_cal, p)) if len(y_cal) else None,
            "auc": float(roc_auc_score(y_cal, p)) if len(y_cal) and y_cal.nunique() >= 2 else None,
            "positiveRate": float(y_cal.mean()) if len(y_cal) else None,
        }
        self.fitted = True
        return self

    def predict_proba(self, X: pd.DataFrame) -> np.ndarray:
        if not self.fitted:
            raise RuntimeError("Model not fitted")
        raw = self.base.predict_proba(X)[:, 1]
        if not self.has_calibrator:
            return raw
        eps = 1e-6
        logits = np.log(np.clip(raw, eps, 1-eps) / np.clip(1-raw, eps, 1-eps)).reshape(-1, 1)
        return self.calibrator.predict_proba(logits)[:, 1]


def feature_table(df: pd.DataFrame, p: Params) -> pd.DataFrame:
    x = features(df, p).copy()
    x["rsi_centered"] = (x.rsi - 50.0) / 50.0
    return x


def _candidate_features(row: pd.Series, side: int, feature_names: Iterable[str]) -> dict:
    values = {
        "rsi_centered": float(row.rsi_centered),
        "sma_gap": float(row.sma_gap),
        "macd_atr": float(row.macd_atr),
        "rv20": float(row.rv20),
        "adx": float(row.adx),
        "ret5": float(row.ret5),
        "bb_z": float(row.bb_z),
        "atr_pct": float(row.atr_pct),
        "ret20": float(row.ret20),
        "ret1": float(row.ret1),
        "range_pct": float(row.range_pct),
        "body_pct": float(row.body_pct),
        "side": float(side),
    }
    return {k: values[k] for k in feature_names}


def build_event_labels(df: pd.DataFrame, p: Params, mlp: MLParams) -> pd.DataFrame:
    """Create candidate events using only signal-bar features and future labels.

    `outcomeEnd` records when the label became knowable; this is used to purge
    overlapping/future information from any later model fit.
    """
    x = feature_table(df, p)
    feat_names = FEATURE_SETS[mlp.feature_set]
    # `side` is generated by the candidate rule and is not a market-data column.
    required = set([c for c in feat_names if c != "side"] + ["atr", "rsi", "sma50"])
    warm = max(p.sma_trend, p.atr_period, p.adx_period, p.bb_period, 30)
    adverse = p.spread_pips * PIP / 2 + p.slippage_pips_per_side * PIP
    rows = []
    for i in range(warm, len(x)-1):
        r = x.iloc[i]
        if any(pd.isna(r.get(c, np.nan)) for c in required):
            continue
        side = broad_candidate_row(r)
        if side == 0:
            continue
        entry_i = i + 1
        entry_row = x.iloc[entry_i]
        entry = float(entry_row.open + adverse if side == 1 else entry_row.open - adverse)
        # Use the current V3.2 structural/volatility risk engine for event labels.
        # The label is still future-looking by definition, but all plan inputs are frozen on the signal bar.
        plan = position_plan(p.initial_capital_eur, entry, side, float(r.atr), r, p)
        if not plan.get("valid", False):
            continue
        raw_stop = float(plan["stopLoss"])
        raw_take = float(plan["takeProfit"])
        exit_px = None
        exit_i = min(entry_i + p.max_holding_bars, len(x)-1)
        reason = "TIME"
        for j in range(entry_i, exit_i + 1):
            rr = x.iloc[j]
            if side == 1:
                if rr.low <= raw_stop:
                    exit_px = raw_stop - adverse; exit_i = j; reason = "SL"; break
                if rr.high >= raw_take:
                    exit_px = raw_take - adverse; exit_i = j; reason = "TP"; break
            else:
                if rr.high >= raw_stop:
                    exit_px = raw_stop + adverse; exit_i = j; reason = "SL"; break
                if rr.low <= raw_take:
                    exit_px = raw_take + adverse; exit_i = j; reason = "TP"; break
        if exit_px is None:
            rr = x.iloc[exit_i]
            exit_px = float(rr.close - adverse if side == 1 else rr.close + adverse)
        unit_pnl = pnl_eur(entry, float(exit_px), 1.0, side) - 2 * (p.commission_per_million_per_side_eur / 1_000_000.0)
        rec = {
            "signalDate": x.index[i], "entryDate": x.index[entry_i], "outcomeEnd": x.index[exit_i],
            "side": side, "label": int(unit_pnl > 0), "unitPnlEUR": float(unit_pnl), "reason": reason,
        }
        rec.update(_candidate_features(r, side, feat_names))
        rows.append(rec)
    return pd.DataFrame(rows)


def fit_model_for_date(events: pd.DataFrame, asof, mlp: MLParams):
    asof = pd.Timestamp(asof)
    train = events[events.outcomeEnd < asof].copy()
    if mlp.max_train_years > 0:
        train = train[train.signalDate >= asof - pd.DateOffset(years=mlp.max_train_years)]
    feat_names = FEATURE_SETS[mlp.feature_set]
    train = train.dropna(subset=feat_names + ["label"]).sort_values("signalDate")
    if len(train) < mlp.min_train_events or train.label.nunique() < 2:
        return None, {"trainingEvents": int(len(train)), "status": "INSUFFICIENT_HISTORY"}
    model = ChronologicalPlattModel(C=mlp.C).fit(train[feat_names], train.label.astype(int), mlp.calibration_fraction)
    meta = {"trainingEvents": int(len(train)), "status": "OK", **model.validation}
    return model, meta


def current_ml_decision(df: pd.DataFrame, p: Params, mlp: MLParams) -> dict:
    x = feature_table(df, p)
    r = x.iloc[-1]
    side = broad_candidate_row(r)
    if side == 0:
        return {"candidate": False, "accepted": False, "side": 0, "probability": None, "status": "NO_CANDIDATE"}
    events = build_event_labels(df.iloc[:-1], p, mlp)
    model, meta = fit_model_for_date(events, x.index[-1], mlp)
    if model is None:
        return {"candidate": True, "accepted": False, "side": side, "probability": None, **meta}
    auc = meta.get("auc")
    if auc is None or not np.isfinite(auc) or auc < mlp.min_validation_auc:
        return {"candidate": True, "accepted": False, "side": side, "probability": None, "status": "MODEL_HEALTH_GATE", **meta}
    feat_names = FEATURE_SETS[mlp.feature_set]
    row = pd.DataFrame([_candidate_features(r, side, feat_names)], index=[x.index[-1]])
    prob = float(model.predict_proba(row)[0])
    return {"candidate": True, "accepted": prob >= mlp.threshold, "side": side, "probability": round(prob, 4),
            "threshold": mlp.threshold, "featureSet": mlp.feature_set, **meta}


def backtest_ml(df: pd.DataFrame, p: Params, mlp: MLParams, start=None, end=None) -> dict:
    """Expanding walk-forward ML meta-filter backtest.

    At every prediction date the training set contains only events whose outcome
    had ended before that date. Retraining occurs every N bars; no future labels
    are used in model selection or sizing.
    """
    x = feature_table(df, p)
    events = build_event_labels(df, p, mlp)
    feat_names = FEATURE_SETS[mlp.feature_set]
    warm = max(p.sma_trend, p.bb_period, p.atr_period, p.adx_period, 30)
    start_ts, end_ts = _utc_ts(start), _utc_ts(end)
    first_i = warm if start_ts is None else max(warm, int(x.index.searchsorted(start_ts, side="left")))
    last_i = len(x)-1 if end_ts is None else min(len(x)-1, int(x.index.searchsorted(end_ts, side="right"))-1)
    if last_i <= first_i:
        raise ValueError("Not enough data for ML backtest window")

    # Align adaptive-risk acceptance with the ML research threshold. Otherwise a
    # candidate accepted at (for example) 0.55 could be sized to zero by a 0.60
    # risk-layer threshold. Direction remains controlled by ML acceptance.
    risk_p = replace(p, ml_probability_threshold=mlp.threshold)

    capital = p.initial_capital_eur
    position = 0; units = 0.0
    entry = stop = take = np.nan
    entry_i = None; entry_date = signal_date = None
    active_plan = None; active_prob = None
    pending = None
    trades = []; eq = []; dates = []; exposure = 0
    adverse = p.spread_pips * PIP / 2 + p.slippage_pips_per_side * PIP
    model = None; model_meta = {}; last_fit_i = -10**9
    prediction_log = []
    candidate_count = accepted_count = rejected_count = 0

    for i in range(first_i, last_i+1):
        r = x.iloc[i]
        if position == 0 and pending is not None:
            position = int(pending["side"])
            entry = float(r.open + adverse if position == 1 else r.open - adverse)
            active_plan = position_plan(capital, entry, position, float(pending["atr"]), pending["row"], risk_p, pending["probability"])
            units = float(active_plan["recommended"]["units"])
            if units <= 0:
                position = 0; pending = None
            else:
                capital -= _commission(units, p)
                stop = float(active_plan["stopLoss"]); take = float(active_plan["takeProfit"])
                entry_i = i; entry_date = x.index[i]; signal_date = pending["signal_date"]
                active_prob = pending["probability"]; pending = None

        reason = raw_exit = None
        if position:
            exposure += 1
            if position == 1:
                if r.low <= stop: reason, raw_exit = "SL", stop
                elif r.high >= take: reason, raw_exit = "TP", take
            else:
                if r.high >= stop: reason, raw_exit = "SL", stop
                elif r.low <= take: reason, raw_exit = "TP", take
            if reason is None and i-entry_i >= p.max_holding_bars:
                reason, raw_exit = "TIME", float(r.close)
            if reason:
                exit_px = float(raw_exit - adverse if position == 1 else raw_exit + adverse)
                pnl = pnl_eur(entry, exit_px, units, position) - _commission(units, p)
                capital += pnl
                trades.append({
                    "signalDate": str(signal_date), "entry": str(entry_date), "exit": str(x.index[i]),
                    "side": "LONG" if position == 1 else "SHORT", "entryPrice": round(entry,6), "exitPrice": round(exit_px,6),
                    "stopLoss": round(stop,6), "takeProfit": round(take,6), "units": round(units,0), "lots": round(units/100000,4),
                    "notionalEUR": round(units,2), "leverage": active_plan["recommended"]["leverage"],
                    "usesLeverage": active_plan["recommended"]["usesLeverage"], "appliedRiskPct": active_plan["appliedRiskPct"],
                    "mlProbability": round(float(active_prob),4), "profitEUR": round(float(pnl),2), "reason": reason,
                })
                position = 0; units = 0.0; entry_i = entry_date = signal_date = None; active_plan = active_prob = None

        mtm = capital
        if position:
            mark = float(r.close - adverse + p.slippage_pips_per_side*PIP if position == 1 else r.close + adverse - p.slippage_pips_per_side*PIP)
            mtm += pnl_eur(entry, mark, units, position)
        eq.append(mtm); dates.append(x.index[i])

        if position == 0 and pending is None and i < last_i:
            side = broad_candidate_row(r)
            if side and not any(pd.isna(r.get(c, np.nan)) for c in feat_names if c != "side"):
                candidate_count += 1
                if model is None or i-last_fit_i >= mlp.retrain_every_bars:
                    model, model_meta = fit_model_for_date(events, x.index[i], mlp)
                    last_fit_i = i
                if model is not None:
                    auc = model_meta.get("auc")
                    healthy = auc is not None and np.isfinite(auc) and auc >= mlp.min_validation_auc
                    row_df = pd.DataFrame([_candidate_features(r, side, feat_names)], index=[x.index[i]])
                    prob = float(model.predict_proba(row_df)[0]) if healthy else float("nan")
                    accepted = bool(healthy and prob >= mlp.threshold)
                    if accepted: accepted_count += 1
                    else: rejected_count += 1
                    prediction_log.append({"signalDate": str(x.index[i]), "side": side, "probability": prob,
                                           "accepted": accepted, "trainingEvents": model_meta.get("trainingEvents",0)})
                    if accepted:
                        pending = {"side": side, "signal_date": x.index[i], "atr": float(r.atr), "row": r.copy(), "probability": prob}

    if position:
        r = x.iloc[last_i]
        exit_px = float(r.close - adverse if position == 1 else r.close + adverse)
        pnl = pnl_eur(entry, exit_px, units, position) - _commission(units, p)
        capital += pnl
        trades.append({"signalDate": str(signal_date), "entry": str(entry_date), "exit": str(x.index[last_i]),
                       "side": "LONG" if position == 1 else "SHORT", "entryPrice": round(entry,6), "exitPrice": round(exit_px,6),
                       "stopLoss": round(stop,6), "takeProfit": round(take,6), "units": round(units,0), "lots": round(units/100000,4),
                       "notionalEUR": round(units,2), "leverage": active_plan["recommended"]["leverage"],
                       "usesLeverage": active_plan["recommended"]["usesLeverage"], "appliedRiskPct": active_plan["appliedRiskPct"],
                       "mlProbability": round(float(active_prob),4), "profitEUR": round(float(pnl),2), "reason": "EOD"})
        eq[-1] = capital

    equity = pd.Series(eq, index=dates, name="equity_eur", dtype=float)
    metrics = _metrics(equity, trades, p.initial_capital_eur, capital, exposure)
    metrics.update({
        "mlCandidateSignals": int(candidate_count),
        "mlAcceptedSignals": int(accepted_count),
        "mlRejectedSignals": int(rejected_count),
        "mlAcceptanceRatePct": round(accepted_count / candidate_count * 100, 2) if candidate_count else 0.0,
    })
    return {"metrics": metrics, "trades": trades, "equity": equity, "predictions": prediction_log, "lastModelMeta": model_meta}
